### ISSUE TITLE
Bordel un peu ;)

### ISSUE THREAD

**Issue by emeric254** [matthieupenchenat81/sociologie#1]
evite de mettre les fichiers intermediaires (style les .log, .aux ...etc...) met juste les sources et le rendu ( .pdf j'imagine parce que le .dvi bah les profs c'est pas leur truc x)
Et l'ortographe doit être capitale sur ce type de projet, bonne chance !
 ;P

**Comment by matthieupenchenat81** [comment]
Mdr oui c'est vrai tu as raison :) c'est plus propre sans les fichiers useless, et.. Tu as vu beaucoup de fautes? 
Pourtant je l'ai passé au correcteur .. :') 

Sent from myMail for iOS

**Comment by emeric254** [comment]
juste pour la première page sur un rapide coup d'oeil ;)

Quel**LE** est la part européenne du lien social?

**Comment by matthieupenchenat81** [comment]
Ok dac thx ;)

Sent from myMail for iOS
